version: "3.9"
services:
  unifi-video:
    # restart: unless-stopped
    build: "./"
    privileged: true
    volumes: 
      - ./data:/var/lib/unifi-video
      - ./recordings:/var/lib/unifi-video/videos
    ports:
      - 6666:6666
      - 7442:7442
      - 7443:7443
      - 7445:7445
      - 7446:7446